### ISSUE TITLE
[DEMO] Error on place order 

### ISSUE THREAD

**Issue by smeubank** [getsentry/opentelemetry-demo#23]
OOTB Error on place order does not respond at all, lets make this an error from a down stream service which can bubble up to the FE in the UI

**Comment by AbhiPrasad** [comment]
Re-opening as prod still seems to be broken. Need to investigate more.

**Comment by AbhiPrasad** [comment]
```
2023-01-17 13:09:23 Error: 2 UNKNOWN: 
2023-01-17 13:09:23     at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
2023-01-17 13:09:23     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
2023-01-17 13:09:23     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
2023-01-17 13:09:23     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
2023-01-17 13:09:23     at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
2023-01-17 13:09:23     at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
2023-01-17 13:09:23   code: 2,
2023-01-17 13:09:23   details: '',
2023-01-17 13:09:23   metadata: Metadata {
2023-01-17 13:09:23     internalRepr: Map(1) { 'content-type' => [Array] },
2023-01-17 13:09:23     options: {}
2023-01-17 13:09:23   }
2023-01-17 13:09:23 }
2023-01-17 13:09:27 Error: 2 UNKNOWN: Exception calling application: Unsupported scheme ''
2023-01-17 13:09:27     at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
2023-01-17 13:09:27     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
2023-01-17 13:09:27     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
2023-01-17 13:09:27     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
2023-01-17 13:09:27     at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
2023-01-17 13:09:27     at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
2023-01-17 13:09:27   code: 2,
2023-01-17 13:09:27   details: "Exception calling application: Unsupported scheme ''",
2023-01-17 13:09:27   metadata: Metadata {
2023-01-17 13:09:27     internalRepr: Map(1) { 'content-type' => [Array] },
2023-01-17 13:09:27     options: {}
2023-01-17 13:09:27   }
2023-01-17 13:09:27 }
```

For some reason we get `Exception calling application`.

**Comment by AbhiPrasad** [comment]
Alright seems to be fixed with https://github.com/getsentry/opentelemetry-demo/pull/46, but fingers crossed
